# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\William\Desktop\测控系统\MCS\mcs.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCS(object):
    def setupUi(self, MCS):
        MCS.setObjectName("MCS")
        MCS.resize(797, 720)
        MCS.setMinimumSize(QtCore.QSize(780, 720))
        MCS.setAccessibleName("")
        self.centralWidget = QtWidgets.QWidget(MCS)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setMinimumSize(QtCore.QSize(74, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(137, 0))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setMinimumSize(QtCore.QSize(74, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 4, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 4, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 3, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.groupBox_4)
        self.horizontalScrollBar.setMinimum(1)
        self.horizontalScrollBar.setMaximum(1000)
        self.horizontalScrollBar.setProperty("value", 1)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout_4.addWidget(self.horizontalScrollBar)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 1, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MCS.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MCS)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 797, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menuColor_Setting = QtWidgets.QMenu(self.menu_2)
        self.menuColor_Setting.setObjectName("menuColor_Setting")
        self.menuSignal = QtWidgets.QMenu(self.menu_2)
        self.menuSignal.setObjectName("menuSignal")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MCS.setMenuBar(self.menuBar)
        self.actionsome_help = QtWidgets.QAction(MCS)
        self.actionsome_help.setObjectName("actionsome_help")
        self.actionabout_some = QtWidgets.QAction(MCS)
        self.actionabout_some.setObjectName("actionabout_some")
        self.actionNew = QtWidgets.QAction(MCS)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MCS)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Recently = QtWidgets.QAction(MCS)
        self.actionOpen_Recently.setObjectName("actionOpen_Recently")
        self.actionSave = QtWidgets.QAction(MCS)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MCS)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionBackgroud_Color = QtWidgets.QAction(MCS)
        self.actionBackgroud_Color.setObjectName("actionBackgroud_Color")
        self.actionLine_Color = QtWidgets.QAction(MCS)
        self.actionLine_Color.setObjectName("actionLine_Color")
        self.actionPoint_Color = QtWidgets.QAction(MCS)
        self.actionPoint_Color.setObjectName("actionPoint_Color")
        self.actionExport_Data = QtWidgets.QAction(MCS)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionExport_Data_As = QtWidgets.QAction(MCS)
        self.actionExport_Data_As.setObjectName("actionExport_Data_As")
        self.action_Exit = QtWidgets.QAction(MCS)
        self.action_Exit.setObjectName("action_Exit")
        self.actionSquare = QtWidgets.QAction(MCS)
        self.actionSquare.setCheckable(True)
        self.actionSquare.setChecked(True)
        self.actionSquare.setObjectName("actionSquare")
        self.actionTriangle = QtWidgets.QAction(MCS)
        self.actionTriangle.setCheckable(True)
        self.actionTriangle.setObjectName("actionTriangle")
        self.actionSin = QtWidgets.QAction(MCS)
        self.actionSin.setCheckable(True)
        self.actionSin.setObjectName("actionSin")
        self.actionStyle_Sheet = QtWidgets.QAction(MCS)
        self.actionStyle_Sheet.setObjectName("actionStyle_Sheet")
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionOpen_Recently)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSave_As)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExport_Data)
        self.menu.addAction(self.actionExport_Data_As)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Exit)
        self.menuColor_Setting.addAction(self.actionBackgroud_Color)
        self.menuColor_Setting.addAction(self.actionLine_Color)
        self.menuColor_Setting.addAction(self.actionPoint_Color)
        self.menuSignal.addAction(self.actionSquare)
        self.menuSignal.addAction(self.actionTriangle)
        self.menuSignal.addAction(self.actionSin)
        self.menu_2.addAction(self.menuSignal.menuAction())
        self.menu_2.addAction(self.menuColor_Setting.menuAction())
        self.menu_2.addAction(self.actionStyle_Sheet)
        self.menu_3.addAction(self.actionsome_help)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionabout_some)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MCS)
        QtCore.QMetaObject.connectSlotsByName(MCS)

    def retranslateUi(self, MCS):
        _translate = QtCore.QCoreApplication.translate
        MCS.setWindowTitle(_translate("MCS", "MCS(测控系统课程软件设计)"))
        self.groupBox.setTitle(_translate("MCS", "采样波形"))
        self.groupBox_2.setTitle(_translate("MCS", "采样波形FFT"))
        self.groupBox_6.setTitle(_translate("MCS", "信号特征"))
        self.label.setText(_translate("MCS", "最大幅值 (V)"))
        self.label_3.setText(_translate("MCS", "周期 (μs)"))
        self.label_2.setText(_translate("MCS", "频率 (kHz)"))
        self.groupBox_3.setTitle(_translate("MCS", "输入电压选择"))
        self.radioButton_2.setText(_translate("MCS", "0 ~ 10 V"))
        self.radioButton_4.setText(_translate("MCS", "-10 ~ +10 V"))
        self.radioButton_3.setText(_translate("MCS", "-5 ~ +5 V"))
        self.radioButton.setText(_translate("MCS", "0 ~ 5 V"))
        self.groupBox_4.setTitle(_translate("MCS", "AD Timer"))
        self.label_4.setText(_translate("MCS", "采样频率 (kHz)"))
        self.lineEdit_4.setText(_translate("MCS", "0.1"))
        self.groupBox_7.setTitle(_translate("MCS", "采样设置"))
        self.pushButton.setText(_translate("MCS", "开始采样/恢复数据"))
        self.pushButton_2.setText(_translate("MCS", "停止采样"))
        self.pushButton_3.setText(_translate("MCS", "静态显示"))
        self.pushButton_9.setText(_translate("MCS", "采样数据"))
        self.groupBox_5.setTitle(_translate("MCS", "波形设置"))
        self.pushButton_5.setText(_translate("MCS", "缩放"))
        self.pushButton_6.setText(_translate("MCS", "拖动"))
        self.pushButton_4.setText(_translate("MCS", "还原采样波形"))
        self.pushButton_8.setText(_translate("MCS", "还原FFT"))
        self.pushButton_7.setText(_translate("MCS", "保存"))
        self.pushButton_10.setText(_translate("MCS", "频率设置"))
        self.menu.setTitle(_translate("MCS", "File(&F)"))
        self.menu_2.setTitle(_translate("MCS", "View(&V)"))
        self.menuColor_Setting.setTitle(_translate("MCS", "Color Setting"))
        self.menuSignal.setTitle(_translate("MCS", "Signal"))
        self.menu_3.setTitle(_translate("MCS", "Help(&H)"))
        self.actionsome_help.setText(_translate("MCS", "MCS Help"))
        self.actionsome_help.setShortcut(_translate("MCS", "Ctrl+Shift+/"))
        self.actionabout_some.setText(_translate("MCS", "About MCS"))
        self.actionNew.setText(_translate("MCS", "New..."))
        self.actionNew.setShortcut(_translate("MCS", "Ctrl+N"))
        self.actionOpen.setText(_translate("MCS", "Open..."))
        self.actionOpen.setShortcut(_translate("MCS", "Ctrl+O"))
        self.actionOpen_Recently.setText(_translate("MCS", "Open Recent"))
        self.actionSave.setText(_translate("MCS", "Save Image"))
        self.actionSave.setShortcut(_translate("MCS", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MCS", "Save As..."))
        self.actionBackgroud_Color.setText(_translate("MCS", "Backgroud Color"))
        self.actionLine_Color.setText(_translate("MCS", "Line Color"))
        self.actionPoint_Color.setText(_translate("MCS", "Point Color"))
        self.actionExport_Data.setText(_translate("MCS", "Export Data"))
        self.actionExport_Data_As.setText(_translate("MCS", "Export Data As..."))
        self.action_Exit.setText(_translate("MCS", "Exit"))
        self.action_Exit.setShortcut(_translate("MCS", "Ctrl+Q"))
        self.actionSquare.setText(_translate("MCS", "Square"))
        self.actionTriangle.setText(_translate("MCS", "Triangle "))
        self.actionSin.setText(_translate("MCS", "Sine"))
        self.actionStyle_Sheet.setText(_translate("MCS", "Style Sheet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MCS = QtWidgets.QMainWindow()
    ui = Ui_MCS()
    ui.setupUi(MCS)
    MCS.show()
    sys.exit(app.exec_())
